version: '2.1'
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cimg/node:20.12.1
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm install && make test-coverage
      - coveralls/upload
  python-tests:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Python tests
          command: pytest
      - run:
          name: Static Analysis with Flake8
          command: |
            pip install flake8
            flake8
  node-tests:
    docker:
      - image: cimg/node:20.12.1
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Jest
          command: npm install --save-dev jest
      - run:
          name: Run Jest tests
          command: npm test
  cypress-tests:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - run:
          name: Run Cypress tests
          command: npm run cy:run
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - python-tests
      - node-tests
      - cypress-tests
      
