version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Python tests
          command: pytest
      - run:
          name: Static Analysis with Flake8
          command: |
            pip install flake8
            flake8
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get update
            sudo apt-get install -y nodejs npm
      - run:
          name: Install Jest
          command: npm install --save-dev jest
      - run:
          name: Run Jest tests
          command: npm test
