version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Python tests
          command: pytest
      - run:
          name: Static Analysis with Flake8
          command: |
            pip install flake8
            flake8
      - run:
          name: Install Node.js and npm
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
      - run:
          name: Install JavaScript dependencies
          command: npm install
      - run:
          name: Run Jest tests
          command: npm test
