version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
      # - image: cimg/node:20.12.1
      #  environment:
      #   CI: true
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Python tests
          command: pytest
      - run:
          name: Static Analysis with Flake8
          command: |
            pip install flake8
            flake8
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Jest
          command: npm install --save-dev jest
    #  - run:
    #     name: Run Jest tests
    #     command: npm test
